id = "lunes"
name = "Lunes"
version = "0.0.1"
schema_version = 1
authors = ["BurningHot687"]
description = "A middle ground between the VSC Lunar Blue theme and One Dark"
repository = "https://github.com/your-name/my-zed-extension"